#include "ejson.h"

//char json_str[] = "{\"Name\":\"Manu\", \"Age\":100, \"Details\":{\"address\":\"kollam\", \"phone\":101}}";
char json_str[] = "[\n"
"\t{\n"
"\t\t\"id\": \"0001\",\n"
"\t\t\"type\": \"donut\",\n"
"\t\t\"name\": \"Cake\",\n"
"\t\t\"ppu\": 0.55,\n"
"\t\t\"batters\":\n"
"\t\t\t{\n"
"\t\t\t\t\"batter\":\n"
"\t\t\t\t\t[\n"
"\t\t\t\t\t\t{ \"id\": \"1001\", \"type\": \"Regular\" },\n"
"\t\t\t\t\t\t{ \"id\": \"1002\", \"type\": \"Chocolate\" },\n"
"\t\t\t\t\t\t{ \"id\": \"1003\", \"type\": \"Blueberry\" },\n"
"\t\t\t\t\t\t{ \"id\": \"1004\", \"type\": \"Devil's Food\" }\n"
"\t\t\t\t\t]\n"
"\t\t\t},\n"
"\t\t\"topping\":\n"
"\t\t\t[\n"
"\t\t\t\t{ \"id\": \"5001\", \"type\": \"None\" },\n"
"\t\t\t\t{ \"id\": \"5002\", \"type\": \"Glazed\" },\n"
"\t\t\t\t{ \"id\": \"5005\", \"type\": \"Sugar\" },\n"
"\t\t\t\t{ \"id\": \"5007\", \"type\": \"Powdered Sugar\" },\n"
"\t\t\t\t{ \"id\": \"5006\", \"type\": \"Chocolate with Sprinkles\" },\n"
"\t\t\t\t{ \"id\": \"5003\", \"type\": \"Chocolate\" },\n"
"\t\t\t\t{ \"id\": \"5004\", \"type\": \"Maple\" }\n"
"\t\t\t]\n"
"\t},\n"
"\t{\n"
"\t\t\"id\": \"0002\",\n"
"\t\t\"type\": \"donut\",\n"
"\t\t\"name\": \"Raised\",\n"
"\t\t\"ppu\": 0.55,\n"
"\t\t\"batters\":\n"
"\t\t\t{\n"
"\t\t\t\t\"batter\":\n"
"\t\t\t\t\t[\n"
"\t\t\t\t\t\t{ \"id\": \"1001\", \"type\": \"Regular\" }\n"
"\t\t\t\t\t]\n"
"\t\t\t},\n"
"\t\t\"topping\":\n"
"\t\t\t[\n"
"\t\t\t\t{ \"id\": \"5001\", \"type\": \"None\" },\n"
"\t\t\t\t{ \"id\": \"5002\", \"type\": \"Glazed\" },\n"
"\t\t\t\t{ \"id\": \"5005\", \"type\": \"Sugar\" },\n"
"\t\t\t\t{ \"id\": \"5003\", \"type\": \"Chocolate\" },\n"
"\t\t\t\t{ \"id\": \"5004\", \"type\": \"Maple\" }\n"
"\t\t\t]\n"
"\t},\n"
"\t{\n"
"\t\t\"id\": \"0003\",\n"
"\t\t\"type\": \"donut\",\n"
"\t\t\"name\": \"Old Fashioned\",\n"
"\t\t\"ppu\": 0.55,\n"
"\t\t\"batters\":\n"
"\t\t\t{\n"
"\t\t\t\t\"batter\":\n"
"\t\t\t\t\t[\n"
"\t\t\t\t\t\t{ \"id\": \"1001\", \"type\": \"Regular\" },\n"
"\t\t\t\t\t\t{ \"id\": \"1002\", \"type\": \"Chocolate\" }\n"
"\t\t\t\t\t]\n"
"\t\t\t},\n"
"\t\t\"topping\":\n"
"\t\t\t[\n"
"\t\t\t\t{ \"id\": \"5001\", \"type\": \"None\" },\n"
"\t\t\t\t{ \"id\": \"5002\", \"type\": \"Glazed\" },\n"
"\t\t\t\t{ \"id\": \"5003\", \"type\": \"Chocolate\" },\n"
"\t\t\t\t{ \"id\": \"5004\", \"type\": \"Maple\" }\n"
"\t\t\t]\n"
"\t}\n"
"]";
int main(){
   char key[] = "topping";
   char key_ph[] = "phone";
   char res1[5000];
   char res2[1000]; 
   ejson_get_attribute(json_str, key, res1);
  printf("Details: [%s]\r\n", res1);
   //ejson_get_attribute(res1, key_ph, res2);
   //printf("Phone: [%s]\r\n", res2);
}